apiVersion: v1
kind: Secret
metadata:
    name: thriftserver-server-conf
    labels:
        app: thriftserver
    annotations:
        kustomize.config.k8s.io/behavior: replace
stringData:
    thrift-server.conf: ENC[AES256_GCM,data:0XcMGcp0BEP6tR2Vy+dTfKE9Nr2igVs7T6GfM2VSgEwYEK/CyvLnGv8dZmeFVk8iguODhgQQG+KGfDXrKBw03Xvx4ZOHsS4YvASJr3HerkI0Z9nOpq92CNcxj5a31kcpKeT5Lvp/iqz5ZWee8M3oRQj0ycpiTJx2oU82/gFGvv0WdMQIyYSBFjVtytY2nixJXUvCvqrxYF/CSyROwKc4+PJiBBZ5rU7n7YzDwfAi8lxj051k3kcKG0T8lWalqmOpfPNOrtmvUTiOugRsmj7qlJHAEJ2VJ+0ulgHnTCoVSXkEwbnMD4JeTou6W7IGI6F/ZeWYJt0ynDbZ5wizIiQSy9yONOzm0veZwVCR/oy7cJ6o3ZA8V4ypo5py6IeHbhaV/MCui/iBHnUwhTzs8gySAaYKIucaqgoDzpIkTuXlj+PNNKlZs09CUTxFjyJZKEgvbUGYzKKTM7D/27d8oOTAM8j6nRUc1Cfp9gSFo3CAxUlFtNlvPT5si5a1AWQRGf3Ec5ICdfnKwric5fsw0EdDxmHm9YYA8OO+KQo/vvFVsJob0N5mg2lM14M4YffB3yU9LtNKRVpVX8Ct2HFgItypb/SCJmfxeUL220XaKl3t/i3xCtowXNqhlWmXtk7BgBymVgOP9hubQv3OBf+fy60utYw4loBoS5TkL9V+zoU1BTt7I4SB0tCqbE+zOPE5cE/XdvtIJk+RJ/JPrqKpK5OqT2uy13qJZ/NqhK6RMLLTvYyibuhFTEuviCqWxw9KAbDycC+WHQAOMhXBdiy2aR/Z0jQ82y1TuOTfAvro/LoPqAFT5NA3YSdqd53xvSvOn5uM59xiHpsoHh6TtT5FkI1hCIthZFi/NPcQB9wjQoXCgeIQRwJM3djMpMJbP9mJCEvtgqbYzrdP8udft2yLepA5K+k2G1umYE4+TCKYWC59mWKYQV0ooMHmUrENMCDmx5rofrfgwAfrC+ut5uVtE3p4akA96HzvGDiiME2F3YsSE/eKDntqv6Is+XEw9558pMZfd2Jf7YJLMEsfHsK8Dm9noMbicYVAns3D+QOP76EUVPJob9lQu0LZQ+1JL9SqUSgefZkPrJjMJ1UDEm2vG5Os7GCxF4FyynOhDY/6Lk4iS2CMINzBzBecAGK0DQTRaOnuX/RlHioI/Eu1/AMTPslhdNsdvAoiBmxW9i0a30BCYorLe1vFPzAkoP4lsdzvdXTyoJO7teq79RAZ6py7FwYANmbiOl/lqGAUzRnnJZr87zz7Z9r6+bxXyWN/QsSU/paeT2M/gBU0pXsgjVihMn5K3kX4kb5ehfFGGMs+MAjEjHGa5ynXGvRbfC0ka+DpCDB2fcqhPW3Fhjgt16jQfizM2XAHocP0J8YGvBeJQ+X1oKfXeB607aFE/feTX45vvAhee05/n95puvh4FImTCW4rBshHwXQ39ivo5RKVjT8wq0JTa+nXB1ke7yKIg0SLgdQ/wrBiHR9TpzNxayV+yb5KgPHB8WRc9R3jc4BFjuRIVSkSzNLO+7yc5JuOJ8CGL51HlUFB96/uheXhECUjvKj2QlvQUGjURwg+/ZypNpKxlYlCegHjdz0Yragp+iZlMaATfjwwZKeoLk7QvnBrj1sIygnlqJa7lIOWL3KblTLY3dsUNgXIFvDbz+fww2miQsHM0r3SOkK9r4f2mAKnc6R4rNs6QjSB,iv:hYRk5csfpPRECY0vYnmnAEjaVtDq8r7drvWmhgEgkAA=,tag:VpBXhiqGlORri74SNBjjiQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-07-28T14:41:38Z'
    mac: ENC[AES256_GCM,data:JRXCGEY2jRL/DtmL0lsuCnCQAwgIpQRMA85+w7G/NUmAqMFD+DLpaKLbfmaUry5v/myZkZW+6PD8Hi6CMq8SCoUFU0mpVQd1NZeItnxfsWVXoWYICDcMh0Ag2qMc1R7L3Hv1Btunu8MyA9mcNRectjYITrQ0Ht9vHWLRJs4bGR4=,iv:7XgX6jjB6raw/8uE2qDlYPKg40SOMNemxmgT7YFFd3Q=,tag:+WHyaCZKXL+5sPzuY9kf6g==,type:str]
    pgp:
    -   created_at: '2021-03-30T14:05:53Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA/irrHa183bxAQf+NQtfDXSid8beUsU/hv7+HYsHSfBtTibC9wfgQaKKfcI8
            70OsWmxysUULMYj1pCA6AvxpCX+h023jJNJcAK6IE3sN68hcHgaa3XHVl2uskN+r
            Rimj7vJbEo2ATOAdxUBOjArH1plA5idRFBW9yq4j8skTMZUKlomjiRQJo961vsvl
            SELMo6LaLQwmGYWhbZyb/KGjEjylALnZkm7QGbRP/Ip55wP/6QQb1abbikRs22oK
            p6Jsw5dx878TGYXOKQDnmVSt2cZUTjIFDmIEJpkRe4EAQSBuEtNkhdt6Ni8CadK3
            fjJsCL3c7Yh3extRkgC9tb9VWh86BQfJKQtHjAY/HNJeAUe9BH8sly2S9/SzBbUY
            pyt+opVehcguuM5P4JvEMQIolBrN27VBIq83Q24auF7VWtTgVqhm40WriD5k5VUr
            luL2n9oGcOW/3m53BWCLhHco+ZiIQyzLUfWIrf3RfA==
            =eRyR
            -----END PGP MESSAGE-----
        fp: EFDB9AFBD18936D9AB6B2EECBD2C73FF891FBC7E
    encrypted_regex: ^(data|stringData|tls)$
    version: 3.6.1
