---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-spark-minimal-notebook-with-libsndfile

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-spark-minimal-notebook-with-libsndfile
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-spark-minimal-notebook-with-libsndfile:3.6'
  resources:
    limits:
      memory: 1Gi
  source:
    contextDir: minimal-notebook
    git:
      uri: 'https://github.com/aakankshaduggal/jupyter-notebooks'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'quay.io/aduggal/python36-spark-ubi7-with-libsndfile:latest'
    type: Source
  triggers:
    - type: ConfigChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-spark-scipy-notebook-with-libsndfile

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: s2i-spark-scipy-notebook-with-libsndfile
  name: s2i-spark-scipy-notebook-with-libsndfile
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-spark-scipy-notebook-with-libsndfile:3.6
  resources:
    limits:
      memory: 1Gi
  source:
    contextDir: scipy-notebook
    git:
      uri: https://github.com/aakankshaduggal/jupyter-notebooks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-spark-minimal-notebook-with-libsndfile:3.6
    type: Source
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-spark24-minimal-notebook

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: s2i-spark24-minimal-notebook
  name: s2i-spark24-minimal-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-spark24-minimal-notebook:3.6
  resources:
    limits:
      memory: 1Gi
  source:
    contextDir: minimal-notebook
    git:
      uri: https://github.com/vpavlin/jupyter-notebooks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: quay.io/vpavlin/python36-spark-ubi7:feature_spark-2.4
    type: Source
  triggers:
    - type: ConfigChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-spark24-scipy-notebook

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-spark24-scipy-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-spark24-scipy-notebook:3.6
  resources:
    limits:
      memory: 1Gi
  source:
    contextDir: scipy-notebook
    git:
      uri: https://github.com/vpavlin/jupyter-notebooks
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-spark24-minimal-notebook:3.6
    type: Source
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-thoth-notebook

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: s2i-thoth-notebook
spec:
  output:
    to:
      kind: ImageStreamTag
      name: s2i-thoth-notebook:3.6
  resources:
    limits:
      memory: 512Mi
  source:
    git:
      ref: master
      uri: https://github.com/thoth-station/jupyter-notebook
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-minimal-notebook:3.6
    type: Source
  triggers:
    - type: ConfigChange
    - type: ImageChange


# AIOps Data Sci Demo images
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-openshift-sme-mailing-list-analysis-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: docker-registry.upshift.redhat.com/aicoe-notebooks/openshift-sme-mailing-list-analysis:latest
    importPolicy:
      scheduled: true
    name: "latest"

## OCP4 Anomaly Detection Image from https://github.com/aicoe-aiops/ocp4-anomaly-detection-internal
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: s2i-ocp4-anomaly-detection-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: docker-registry.upshift.redhat.com/aicoe-notebooks/ocp4-anomaly-detection-internal:latest
    importPolicy:
      scheduled: true
    name: "latest"

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-drift-analysis-notebook
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: docker-registry.upshift.redhat.com/aicoe-notebooks/drift-analysis-baselines:latest
    importPolicy:
      scheduled: true
    name: "latest"

## Categorical encoding image from https://gitlab.corp.redhat.com/aicoe-aiops/categorical-encoding-internal
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-categorical-encoding-notebook
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: docker-registry.upshift.redhat.com/aicoe-notebooks/categorical-encoding-internal:latest
    importPolicy:
      scheduled: true
    name: "latest"

# Thoth Data Sci Demo images
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-dataset-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: docker-registry.upshift.redhat.com/aicoe-notebooks/datasets:latest
    importPolicy:
      scheduled: true
    name: "latest"

# Sentiment Analysis Demo image
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-sentiment-analysis-demo-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: docker-registry.upshift.redhat.com/aicoe-notebooks/sentiment-analysis-demo:latest
    importPolicy:
      scheduled: true
    name: "latest"

# Insight configuration file analysis image
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-insights-configuration-files-analysis-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: docker-registry.upshift.redhat.com/aicoe-notebooks/insights-configuration-files-analysis:latest
    importPolicy:
      scheduled: true
    name: "latest"

# Configuration file analysis image on public dataset
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-configuration-files-analysis-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: docker-registry.upshift.redhat.com/aicoe-notebooks/configuration-files-analysis:latest
    importPolicy:
      scheduled: true
    name: "latest"

# Landon version of s2i-minimal-spark-notebook
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: test-s2i-spark-minimal-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: quay.io/llasmith/s2i-spark-minimal-notebook:spark-3.0_hadoop-3.2.0_jdk-11
    importPolicy:
      scheduled: true
    name: "latest"

# s2i-pytorch-notebook
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-pytorch-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: quay.io/thoth-station/s2i-pytorch-notebook:v0.0.2
    importPolicy:
      scheduled: true
    name: "latest"
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-pytorch-py38-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: quay.io/thoth-station/s2i-pytorch-py38-notebook:latest
    importPolicy:
      scheduled: true
    name: "latest"

# s2i-data-science-notebook
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    opendatahub.io/notebook-image: "true"
  name: s2i-data-science-py38-notebook
spec:
  lookupPolicy:
    local: true
  tags:
  - from:
      kind: DockerImage
      name: quay.io/thoth-station/s2i-generic-data-science-notebook:v0.0.5
    name: "v0.0.5"
    referencePolicy:
      type: Source

---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: s2i-pytorch-notebook-gpu
  labels:
    build: s2i-pytorch-notebook-gpu
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-pytorch-notebook-gpu:latest'
  resources:
    limits:
      memory: 4Gi
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 's2i-minimal-notebook-gpu:latest'
  source:
    type: Git
    git:
      ref: master
      uri: 'https://github.com/thoth-station/s2i-pytorch-notebook'
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: s2i-minimal-notebook-gpu
  name: s2i-minimal-notebook-gpu
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-minimal-notebook-gpu:3.6'
  resources:
    limits:
      memory: 2Gi
  runPolicy: Serial
  source:
    contextDir: minimal-notebook
    git:
      ref: master
      uri: 'https://github.com/vpavlin/jupyter-notebooks'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python-36-ubi7:10.0-cudnn7-devel-ubi7'
    type: Source
  triggers:
    - type: ConfigChange
